@startuml
'https://plantuml.com/sequence-diagram

'autonumber

actor Actor
participant ControllerRcvMeetingService
participant RcvClientJoinMeetingController
participant RcvClientInMeetingController
autoactivate off

Actor -> ControllerRcvMeetingService: joinMeeting
ControllerRcvMeetingService -> RcvClientJoinMeetingController:joinMeeting;
RcvClientJoinMeetingController -> RoomMeetingConnector:joinMeetingWithOptions;
RoomMeetingConnector -> SDK:sendJoinAction
SDK --> HostClientPdUiController:onRequestToJoin
HostClientPdUiController -> RcvMeetingActionHandler: notifyOnActionEvent
RcvMeetingActionHandler -> HostCommunicationService:onUpdateRoomAction
HostCommunicationService -> HostHomePresenter:onAction
HostHomePresenter -> HostRcvJoinMeetingController:joinMeeting

HostRcvJoinMeetingController -> SDK: joinMeeting
SDK --> RoomMeetingConnector:onHostStatusChanged(Connecting)
RoomMeetingConnector -> ControllerRcvMeetingService:onMeetingStateChanged(Joining)
ControllerRcvMeetingService -> RcvClientInMeetingController:init(meetingId, meetingHandler)

SDK --> RoomMeetingConnector:onHostStatusChanged(IN_MEETING)
@enduml