@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Actor
participant RoomsEventManager
entity RoomsEvent
participant RCF
autoactivate on

Actor -> RoomsEventManager: postCustomEvent(name, message, params, priority)
RoomsEventManager -> RoomsEvent **: create
RoomsEventManager -> RCF: postCustomEvent(event, priority)
RCF -> RoomsEventManager: showBanner(event)
@enduml