@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Actor
participant RoomsEventManager
participant RCF
entity RCFEvent
autoactivate on

Actor -> RoomsEventManager: postCustomEvent(name)
RoomsEventManager -> RCF: postCustomEvent(name)
RCF -> RCFEvent **: create
RCF -> RoomsEventManager: showBanner(event)
@enduml