@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "RCV SDK" as RCV
autoactivate on
RCV ->> RCF: updated RCV events

RCF ->> RCF: filter out the Rooms events

RCF -> RoomsEventManager: showBanner

RoomsEventManager -> BannerController: showBanner

BannerController -> BannerItems: generateBannerItems
BannerItems -> AbstractBannerItem **: create
return return supported banner items
BannerController -> BannerController: filter out the supported banners
BannerController -> ControllerBannerFragment: showBanners

ControllerBannerFragment -> AbstractBannerItem: getBannerMessage
return return message
ControllerBannerFragment -> ControllerBannerFragment: update UI

@enduml