@startuml
'https://plantuml.com/component-diagram

interface notifyRcvEvents as NRCV
interface postEvent
interface onEvent

NRCV -d- [RCV SDK]
postEvent -d- [RCF]
onEvent -d- [RCF]


[APP] ..> onEvent: impl
[APP] ..> postEvent: use
[RCF] ..> NRCV: require events
@enduml