@startuml
'https://plantuml.com/component-diagram

interface notifyRcvEvents as NRCV
interface postEvent

NRCV -d- [RCV SDK]
postEvent -d- [RCF]
showBannerList -d- [RCF]
showAlert -d- [RCF]
showToast -d- [RCF]


[APP] ..> showBannerList: impl
[APP] ..> showAlert: impl
[APP] ..> showToast: impl
[APP] ..> postEvent: use
[RCF] ..> NRCV: require events
@enduml