@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

RcvClientInMeetingController -down-|> BaseClientInMeetingController
WebinarPanelistClientInMeetingController -down-|> BaseClientInMeetingController

BaseClientInMeetingController -down-> RCF.RoomMeetingConnector
BaseClientInMeetingController -right-> ClientSharingController
ClientSharingController -down-> RCF.RoomMeetingConnector
ClientSharingController -right-> SharingListener


RCV.ClientPdUiController .down.> RCV.IControllerService
RCF.RoomMeetingConnector .down.> RCV.IControllerService

InstructionLayoutPresenter .down.> ClientSharingController
MeetingShareScreenActionPresenter .down.> ClientSharingController

abstract class BaseClientInMeetingController {
    + sharingController: ClientSharingController
    + onExtendMeetingStatusUpdate(status: IRoomExtendMeetingStatus)
}

class RcvClientInMeetingController {

}

class WebinarPanelistClientInMeetingController {

}

class ClientSharingController {
    + startSharing()
    + stopSharing()
    + registerSharingListener(listener: SharingListener)
    + unregisterSharingListener(listener: SharingListener)
}

interface SharingListener {
    + onSharingStarted(isLocalSharing:Boolean, sharingType:ESharingStatusType)
    + onSharingStopped(isLocalSharing:Boolean, sharingType:ESharingStatusType)
    + onSharingUpdated(isLocalSharing:Boolean, sharingType:ESharingStatusType)
}

class InstructionLayoutPresenter {

}

class MeetingShareScreenActionPresenter {
}

namespace RCF {
    class RoomMeetingConnector {
    }
}

namespace RCV {
    class ClientPdUiController {
    }

    class IControllerService<< (S, #FF7700) >> {
    }
}

@enduml