@startuml
'https://plantuml.com/component-diagram



checkResult -d- [RCV SDK]
notifyVoiceCommandStatus -d- [RCV SDK]
recognition -d- [SpeechRecognition SDK]
notifyHypothesis -d- [SpeechRecognition SDK]
audioRecording -d- [Framework]


[APP] ..> recognition: startListening
[APP] ..> notifyHypothesis: filter by confidence
[APP] ..> checkResult: notifyResult
[APP] ..> notifyVoiceCommandStatus: show corresponding UI
[SpeechRecognition SDK] ..> audioRecording: startAudioRecording

@enduml